apiVersion: v1
kind: ConfigMap
metadata:
  name: wavelen-config
  labels:
    {{- include "wavelen.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: postgres # host.k3d.internal
  POSTGRES_PORT: "5432"   # "5433"
  POSTGRES_DB: wavelen
  LOG_LEVEL: debug