{
  # line too long: it's fine
  "MD013": false, # https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md013.md
  # Conflict with Markdown All in One: create ToC (and it's fine)
  "MD007": false, # https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md007.md
  # conflict with Markdown All in One: create ToC
  "MD010": false, # https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md010.md
  # too much
  "MD059": false,
  # too much
  "MD041": false,
  # not ready for this
  "MD034": false,
  # conflict with another extension
  "MD060": false,
  # using inline html for things like this:
  # https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections
  "MD033": false,
  # https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md036.md
  "MD036": false,
  # Fenced code blocks should have a language specified; good, but annoying
  "MD040": false,
  # header decrement
  "MD001": false,
}
