package collection

import (
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/salandered/strvalid"
)

const (
	MinNameLen = 1
	MaxNameLen = 60
)

var ErrInvalidID = errors.New("invalid collection id")

// 32 hex digits and 4 dashes
const canonicalIDLen = 36

// ID is a uuidv7, generated by the database.
type ID uuid.UUID

func (id ID) String() string { return uuid.UUID(id).String() }

// TODO: move to strvalid
func ParseID(s string) (ID, error) {
	if len(s) != canonicalIDLen {
		return ID{}, fmt.Errorf("%w: %q", ErrInvalidID, s)
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return ID{}, fmt.Errorf("%w: %q", ErrInvalidID, s)
	}
	return ID(parsed), nil
}

type Collection struct {
	ID        ID
	Name      string // free form, not unique
	IsDefault bool
	CreatedAt time.Time
}

var nameCfg = strvalid.UnicodeConfig{
	Subject:  "collection name",
	MinRunes: MinNameLen,
	MaxRunes: MaxNameLen,
}

// NormalizeName trims and validates s.
func NormalizeName(s string) (string, error) {
	name := strvalid.Normalize(s, strvalid.NormalizeConfig{TrimSpaces: true, Lowercase: false})
	if err := strvalid.ValidateUnicode(name, nameCfg); err != nil {
		return "", err
	}
	return name, nil
}
