package collection

import (
	"time"
	"uuid"

	"github.com/salandered/strvalid"
	"github.com/salandered/wavelen/internal/color"
	"github.com/salandered/wavelen/internal/icon"
)

const (
	MinNameLen = 1
	MaxNameLen = 60
)

const (
	DefIconSlug   = icon.Default
	DefIconAccent = color.Hex("#808080")
)

// ID is a uuidv7, generated by the database.
type ID uuid.UUID

func (id ID) String() string { return uuid.UUID(id).String() }

var idCfg = strvalid.UUIDConfig{
	Subject:   "collection id",
	EchoValue: true,
}

func ParseID(s string) (ID, error) {
	parsed, err := strvalid.ParseUUID(s, idCfg)
	if err != nil {
		return ID{}, err
	}
	return ID(parsed), nil
}

type Collection struct {
	ID         ID
	Name       string // free form, not unique
	IconSlug   icon.Slug
	IconAccent color.Hex
	IsDefault  bool
	CreatedAt  time.Time
}

type CreateParams struct {
	Name      string
	Icon      icon.Slug
	Accent    color.Hex
	IsDefault bool
}

var nameCfg = strvalid.UnicodeConfig{
	Subject:  "collection name",
	MinRunes: MinNameLen,
	MaxRunes: MaxNameLen,
}

// NormalizeName trims and validates s.
func NormalizeName(s string) (string, error) {
	name := strvalid.Normalize(s, strvalid.NormalizeConfig{TrimSpaces: true, Lowercase: false})
	if err := strvalid.ValidateUnicode(name, nameCfg); err != nil {
		return "", err
	}
	return name, nil
}
